maxNumberOfBackUps: 2
# some users may wish to cycle through back up files.
#
# for example, with maxNumberOfBackUps: 4, they may
# wish to delete the oldest back up file, and keep only the most recent.
#
#    copy myfile.bak1 to myfile.bak0
#    copy myfile.bak2 to myfile.bak1
#    copy myfile.bak3 to myfile.bak2
#    copy myfile.bak4 to myfile.bak3
#
# the back up will be written to myfile.bak4
cycleThroughBackUps: 1

modifyLineBreaks:
  preserveBlankLines: 1                 # 0/1
  condenseMultipleBlankLinesInto: 1     # 0/1
  oneSentencePerLine:
    manipulateSentences: 1              # 0/1
    removeSentenceLineBreaks: 1         # 0/1
